# Generated by Django 5.1.5 on 2025-02-04 08:12

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('currency_unit', models.CharField(choices=[('vnd', 'Vietnam Dong'), ('dol', 'Dollar')], default='vnd', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', cloudinary.models.CloudinaryField(default='image/upload/v1738591988/240_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws_okujdi.jpg', max_length=255)),
                ('user_role', models.CharField(choices=[('tenan', 'Tenant'), ('innkr', 'Innkeeper'), ('admin', 'Adminstrator')], default='tenan', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HouseArticle',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('contact', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=250)),
                ('approve_state', models.CharField(choices=[('cc', 'Cancel'), ('pd', 'Pending'), ('cf', 'Confirm')], default='pd', max_length=2)),
                ('area', models.FloatField(default=0)),
                ('deposit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.deposit')),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='AcquisitionArticle',
            fields=[
                ('housearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.housearticle')),
                ('allowed_human_quantity', models.IntegerField()),
                ('legal_documents', models.CharField(max_length=20)),
                ('display_image', cloudinary.models.CloudinaryField(default='image/upload/v1738630067/1-mua-nha-cu_yb4v56.jpg', max_length=255)),
                ('house_state', models.CharField(choices=[('em', 'Con trong'), ('ex', 'Dang xu li'), ('ns', 'Khong con cho')], default='em', max_length=2)),
                ('type_acquisition', models.CharField(choices=[('ren', 'Cho thue'), ('buy', 'Mua'), ('odr', 'Dat truoc')], default='ren', max_length=3)),
                ('type_house', models.CharField(choices=[('apar', 'Can ho'), ('home', 'Nha rieng'), ('vill', 'Biet thu'), ('strh', 'Nha mac pho'), ('shph', 'Shop'), ('offc', 'Nha van phong'), ('fact', 'Nha xuong'), ('othr', 'Nha loai khac')], default='home', max_length=4)),
                ('type_ownership', models.CharField(choices=[('full', 'Nguyen can'), ('part', 'Mot phan'), ('room', 'Mot phong'), ('flor', 'Mot tang')], default='full', max_length=4)),
                ('interior_state', models.CharField(choices=[('noye', 'Chua co'), ('have', 'Da co')], default='noye', max_length=4)),
                ('innkeeper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.housearticle', models.Model),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latetitude', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.housearticle', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.housearticle')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', cloudinary.models.CloudinaryField(max_length=255)),
                ('acquisition_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.acquisitionarticle')),
            ],
        ),
        migrations.CreateModel(
            name='LookingArticle',
            fields=[
                ('housearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.housearticle')),
                ('house_state', models.CharField(choices=[('em', 'Con trong'), ('ex', 'Dang xu li'), ('ns', 'Khong con cho')], max_length=2, null=True)),
                ('type_acquisition', models.CharField(choices=[('ren', 'Cho thue'), ('buy', 'Mua'), ('odr', 'Dat truoc')], max_length=3, null=True)),
                ('type_house', models.CharField(choices=[('apar', 'Can ho'), ('home', 'Nha rieng'), ('vill', 'Biet thu'), ('strh', 'Nha mac pho'), ('shph', 'Shop'), ('offc', 'Nha van phong'), ('fact', 'Nha xuong'), ('othr', 'Nha loai khac')], max_length=4, null=True)),
                ('type_ownership', models.CharField(choices=[('full', 'Nguyen can'), ('part', 'Mot phan'), ('room', 'Mot phong'), ('flor', 'Mot tang')], max_length=4, null=True)),
                ('interior_state', models.CharField(choices=[('noye', 'Chua co'), ('have', 'Da co')], max_length=4, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.housearticle', models.Model),
        ),
    ]
